name: pipeline1
on: 
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: this is first build step
         run: echo hello from step 1
       - name: this is Second build step
         run: |
           sleep 10
           echo hello from step 2
       - name: this is Third build step
         run: echo hello from step 2
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: build
    steps:
       - name: this is first test step
         run: ech hello from step 1
         continue-on-error: true
       - name: this is Second test step
         run: |
           sleep 10
           echo hello from step 2
  stage:
    runs-on: ubuntu-latest
    needs: test
    steps:
       - name: this is first stage step
         run: echo hello from step 1
       - name: this is Second stage step
         run: |
           sleep 10
           echo hello from step 2
  deploy:
    runs-on: ubuntu-latest
    needs: stage
    steps:
       - name: this is first prod step
         run: echo hello from step 1
       - name: this is Second prod step
         run: |
           sleep 10
           echo hello from step 2         
